### ISSUE TITLE
Move Class (Or some other way to load in moves)

### ISSUE THREAD

**Issue by Clementsaic** [gShahr/modular-robotics#2]
We will need a way to store loaded-in move information, if you have any ideas for how this might be done best post them as replies here.

Here's what I've thought of so far:

- A move should store coordinate information in an identical manner to the Lattice class, so that comparing the desired cell values in the move to the actual cell values on the lattice is kept fairly simple.
- A move should store the initial position of the moving module relative to its local coordinate system
- A move should store the (desired) final position of the module relative to its initial position (so that it's an offset from the original position)

So for example if we had a move that was encoded like this
```
xx
?!
##
```
where `x` means we need that cell to be empty, `#` means we need that cell to contain a module, `?` is the moving modules initial position and `!` is its final position, the initial position of the moving module would be stored in the move as (0,1) (keeping in mind that in the program (0,0) refers to the top left corner), and the desired final position should be stored as (1,0) which we could then use to update the modules position by just adding the final position offset to the original position of the module.

That's just my ideas though if anyone has any alternative ideas definitely post those so that we can figure out what works best

**Comment by gShahr** [comment]
That seems good. I was thinking of where the user gives a set of allowed moves in strings and the program would utilize built-in set of moves with the underlying representation that you shared above. 

Some more ideas:
- How to apply the move in all possible rotations in n-dimensions
- What if multiple files of the same move are given
